/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.poly.view;

import com.poly.entity.BacSi;
import com.poly.entity.HoaDon;
import com.poly.repository.RepoBacSi;
import com.poly.repository.RepoHoaDon;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manh9
 */
public class From_BacSi1 extends javax.swing.JPanel {
    private RepoBacSi repo = new RepoBacSi();
    private List<BacSi> listBs = new ArrayList<>();
    private DefaultTableModel dtm = new DefaultTableModel();
    /**
     * Creates new form From_BacSi
     */
    public From_BacSi1() {
        initComponents();
        listBs = repo.getAll();
//        loadTable(listBs);
    }

//     public void loadTable(List<BacSi> list){
//        DefaultTableModel dtm = (DefaultTableModel) this.tbBacSi.getModel();
//        dtm.setRowCount(0);
//        for (BacSi bs : list) {
//            dtm.addRow(bs.rowData());
//        }
//     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbBacSi1 = new javax.swing.JTable();

        tbBacSi1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "MaNguoiDung", "ChuyenKhoa", "SoNamKinhNghiem", "TrangThai"
            }
        ));
        jScrollPane2.setViewportView(tbBacSi1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbBacSi1;
    // End of variables declaration//GEN-END:variables
}
