/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.poly.ph49507;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class ViewBenhAn1 extends javax.swing.JPanel {

    private ReposBenhAn rp = new ReposBenhAn();
    private DefaultTableModel mol = new DefaultTableModel();
    private int i = -1;
    private String trangthai;

    /**
     * Creates new form ViewBenhAn1
     */
    public ViewBenhAn1() {
        initComponents();
        fillToTable(rp.getall());
    }

    void fillToTable(ArrayList<BenhAn> list) {
        mol = (DefaultTableModel) tbl_benhan.getModel();
        mol.setRowCount(0);
        for (BenhAn benhAn : list) {
            mol.addRow(benhAn.todatarow());
        }
    }

    void showData(int i) {
        txt_id.setText(tbl_benhan.getValueAt(i, 0).toString());
        txt_benhnhan.setText(tbl_benhan.getValueAt(i, 1).toString());
        txt_bacsi.setText(tbl_benhan.getValueAt(i, 2).toString());
        txt_chandoan.setText(tbl_benhan.getValueAt(i, 3).toString());
        txt_dieutri.setText(tbl_benhan.getValueAt(i, 4).toString());
        txt_ngaykham.setText(tbl_benhan.getValueAt(i, 5).toString());
        txt_ngaylapbenhan.setText(tbl_benhan.getValueAt(i, 6).toString());
        txt_mota.setText(tbl_benhan.getValueAt(i, 7).toString());
        trangthai = tbl_benhan.getValueAt(i, 8).toString();
        if (trangthai.equalsIgnoreCase("Hoàn Thành")) {
            rdo_ht.setSelected(true);
        } else {
            rdo_kht.setSelected(true);
        }

    }

    BenhAn readform() {
        int id;
        int mabenhnhan;
        int mabacsi;
        String chandoan;
        String dieutri;
        String ngaykham;
        String ngaylapbenhan;
        String mota;
        String trangthai;
        id = Integer.parseInt(txt_id.getText());
        mabenhnhan = Integer.parseInt(txt_benhnhan.getText());
        mabacsi = Integer.parseInt(txt_bacsi.getText());
        chandoan = txt_chandoan.getText();
        dieutri = txt_dieutri.getText();
        ngaykham = txt_ngaykham.getText();
        ngaylapbenhan = txt_ngaylapbenhan.getText();
        mota = txt_mota.getText();
        if (rdo_ht.isSelected()) {
            trangthai = "Hoàn Thành ";
        } else {
            trangthai = "Không Hoàn Thành";
        }
        return new BenhAn(id, mabenhnhan, mabacsi, chandoan, dieutri, ngaykham, ngaylapbenhan, mota, trangthai);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        txt_dieutri = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rdo_ht = new javax.swing.JRadioButton();
        rdo_kht = new javax.swing.JRadioButton();
        txt_benhnhan = new javax.swing.JTextField();
        txt_bacsi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_them = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_mota = new javax.swing.JTextArea();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_timkiem = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        txt_chandoan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_benhan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_ngaykham = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_ngaylapbenhan = new javax.swing.JTextField();

        jLabel9.setText("Mã Bác Sĩ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Trạng Thái"));

        buttonGroup1.add(rdo_ht);
        rdo_ht.setText("Hoàn Thành");

        buttonGroup1.add(rdo_kht);
        rdo_kht.setText("Không Hoàn Thành");
        rdo_kht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_khtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(rdo_ht, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(rdo_kht)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_ht)
                    .addComponent(rdo_kht))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("Mô tả");

        btn_them.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_them.setForeground(new java.awt.Color(153, 0, 153));
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/png/add.png"))); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        txt_mota.setColumns(20);
        txt_mota.setRows(5);
        jScrollPane2.setViewportView(txt_mota);

        btn_sua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_xoa.setForeground(new java.awt.Color(255, 0, 0));
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/png/delete.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        btn_timkiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_timkiem.setForeground(new java.awt.Color(51, 0, 255));
        btn_timkiem.setText("Tìm Kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        txt_chandoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_chandoanActionPerformed(evt);
            }
        });

        tbl_benhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã Bệnh Nhân", "Mã Bác Sĩ", "Chân Đoán", "Điều Trị", "Ngày Khám", "Ngày Lập Bệnh Án", "Mô Tả", "Trạng Thái"
            }
        ));
        tbl_benhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_benhanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_benhan);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("BỆNH ÁN");

        jLabel3.setText("Chẩn Đoán");

        jLabel4.setText("Điều Trị");

        jLabel5.setText("Ngày Khám");

        jLabel6.setText("Ngày Lập Bệnh Án");

        jLabel7.setText("Mã Bệnh Nhân");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(txt_chandoan, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(22, 22, 22))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_bacsi)
                                    .addComponent(txt_benhnhan)
                                    .addComponent(txt_dieutri)
                                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)
                                        .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57)
                                        .addComponent(btn_timkiem))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(256, 256, 256)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(txt_ngaykham)
                                                        .addComponent(txt_ngaylapbenhan, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(111, 111, 111)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_them))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ngaykham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(txt_ngaylapbenhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_benhnhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txt_bacsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txt_chandoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_dieutri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoa)
                    .addComponent(btn_them)
                    .addComponent(btn_sua)
                    .addComponent(btn_timkiem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdo_khtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_khtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_khtActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn THÊM không");
        if (chon == 0) {
            i = tbl_benhan.getSelectedRow();
            if (this.readform() != null) {
                if (rp.them(this.readform()) > 0) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    this.fillToTable(rp.getall());
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại");
                }
            }
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn SỬA không ?? ");
        if (chon == 0) {
            i = tbl_benhan.getSelectedRow();
            int ma = Integer.parseInt(tbl_benhan.getValueAt(i, 0).toString());
            if (this.readform() != null) {
                if (rp.sua(ma, this.readform()) > 0) {
                    JOptionPane.showMessageDialog(this, "Sửa thành công");
                    this.fillToTable(rp.getall());
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa thất bại");
                }
            }
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn XÓA không");
        if (chon == 0) {
            i = tbl_benhan.getSelectedRow();
            if (i > 0) {
                int id = Integer.parseInt(tbl_benhan.getValueAt(i, 0).toString());
                if (rp.xoa(id) > 0) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    this.fillToTable(rp.getall());
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng xóa");
            }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        String id = JOptionPane.showInputDialog(null, "Mời nhập ID cần tìm","FORM TÌM KIẾM",1);

        if (rp.tim(id).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy ID");
        } else {
            JOptionPane.showMessageDialog(this, "Có tìm thấy tên");
            this.fillToTable(rp.tim(id));
        }
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void txt_chandoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_chandoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_chandoanActionPerformed

    private void tbl_benhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_benhanMouseClicked
        // TODO add your handling code here:
        i = tbl_benhan.getSelectedRow();
        this.showData(i);
    }//GEN-LAST:event_tbl_benhanMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdo_ht;
    private javax.swing.JRadioButton rdo_kht;
    private javax.swing.JTable tbl_benhan;
    private javax.swing.JTextField txt_bacsi;
    private javax.swing.JTextField txt_benhnhan;
    private javax.swing.JTextField txt_chandoan;
    private javax.swing.JTextField txt_dieutri;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextArea txt_mota;
    private javax.swing.JTextField txt_ngaykham;
    private javax.swing.JTextField txt_ngaylapbenhan;
    // End of variables declaration//GEN-END:variables
}
