/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.poly.ph49507;

import com.formdev.flatlaf.json.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class ViewLichHen1 extends javax.swing.JPanel {

    private ReposLichHen rp = new ReposLichHen();
    private DefaultTableModel mol = new DefaultTableModel();
    private int i = -1;
    private String trangthai;

    /**
     * Creates new form ViewLichHen1
     */
    public ViewLichHen1() {
        initComponents();
        filltotable(rp.getAll());
    }

    void filltotable(ArrayList<LichHen> list) {
        mol = (DefaultTableModel) tbl_lichhen.getModel();
        mol.setRowCount(0);
        for (LichHen lichHen : list) {
            mol.addRow(lichHen.todatarow());
        }
    }

    void showData(int i) {
        txt_id.setText(tbl_lichhen.getValueAt(i, 0).toString());
        txt_mabn.setText(tbl_lichhen.getValueAt(i, 1).toString());
        txt_mabs.setText(tbl_lichhen.getValueAt(i, 2).toString());
        txt_ngayhen.setText(tbl_lichhen.getValueAt(i, 3).toString());
        txt_giohen.setText(tbl_lichhen.getValueAt(i, 4).toString());
        txt_ngaydatlich.setText(tbl_lichhen.getValueAt(i, 5).toString());
        trangthai = tbl_lichhen.getValueAt(i, 6).toString();
        if (trangthai.equalsIgnoreCase("Đã xác nhận")) {
            rdo_xn.setSelected(true);
        } else {
            rdo_cxn.setSelected(true);
        }
    }

    LichHen readform() throws java.text.ParseException {
        int id;
        int mabenhnhan;
        int mabacsi;
        String ngayhen;
        String giohen;
        String ngaydatlich;
        String trangthai;

        // Kiểm tra ID
        try {
            id = Integer.parseInt(txt_id.getText());
            if (id <= 0) {
                JOptionPane.showMessageDialog(this, "ID phải là số nguyên dương.");
                return null;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID không hợp lệ.");
            return null;
        }

        // Kiểm tra mã bệnh nhân
        try {
            mabenhnhan = Integer.parseInt(txt_mabn.getText());
            if (mabenhnhan <= 0) {
                JOptionPane.showMessageDialog(this, "Mã bệnh nhân phải là số nguyên dương.");
                return null;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Mã bệnh nhân không hợp lệ.");
            return null;
        }

        // Kiểm tra mã bác sĩ
        try {
            mabacsi = Integer.parseInt(txt_mabs.getText());
            if (mabacsi <= 0) {
                JOptionPane.showMessageDialog(this, "Mã bác sĩ phải là số nguyên dương.");
                return null;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Mã bác sĩ không hợp lệ.");
            return null;
        }

        // Kiểm tra ngày hẹn
        ngayhen = txt_ngayhen.getText();
        if (!isValidDate(ngayhen)) {
            JOptionPane.showMessageDialog(this, "Ngày hẹn không hợp lệ");
            return null;
        }

        // Kiểm tra giờ hẹn
        giohen = txt_giohen.getText();
        if (giohen.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Giờ hẹn không được để trống");
            return null;
        }

        // Kiểm tra ngày đặt lịch
        ngaydatlich = txt_ngaydatlich.getText();
        if (!isValidDate(ngaydatlich)) {
            JOptionPane.showMessageDialog(this, "Ngày đặt lịch không hợp lệ");
            return null;
        }

        // Kiểm tra trạng thái
        if (rdo_xn.isSelected()) {
            trangthai = "Đã xác nhận";
        } else {
            trangthai = "Chưa xác nhận";
        }
        return new LichHen(id, mabenhnhan, mabacsi, ngayhen, giohen, ngaydatlich, trangthai);
    }

    private boolean isValidDate(String date) throws java.text.ParseException {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            sdf.setLenient(false);
            sdf.parse(date);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_tk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_lichhen = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rdo_xn = new javax.swing.JRadioButton();
        rdo_cxn = new javax.swing.JRadioButton();
        txt_id = new javax.swing.JTextField();
        txt_mabn = new javax.swing.JTextField();
        txt_mabs = new javax.swing.JTextField();
        txt_ngayhen = new javax.swing.JTextField();
        txt_giohen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_ngaydatlich = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        btn_them.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_them.setForeground(new java.awt.Color(153, 0, 153));
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/png/add.png"))); // NOI18N
        btn_them.setText("Thêm Lịch Hẹn");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/png/clear.png"))); // NOI18N
        btn_sua.setText("Sửa Lịch Hẹn");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_xoa.setForeground(new java.awt.Color(255, 0, 0));
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/png/delete.png"))); // NOI18N
        btn_xoa.setText("Xóa Lịch Hẹn");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_tk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_tk.setForeground(new java.awt.Color(0, 0, 255));
        btn_tk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/png/filter-filled-tool-symbol.png"))); // NOI18N
        btn_tk.setText("Tìm Kiếm Lịch Hẹn");
        btn_tk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tkActionPerformed(evt);
            }
        });

        tbl_lichhen.setForeground(new java.awt.Color(51, 204, 255));
        tbl_lichhen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã Bệnh Nhân", "Mã Bác Sĩ", "Ngày Hẹn", "Giờ Hẹn", "Ngày Đặt Lịch", "Trạng Thái"
            }
        ));
        tbl_lichhen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_lichhenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_lichhen);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("ID");

        jLabel2.setForeground(new java.awt.Color(51, 204, 255));
        jLabel2.setText("Mã Bệnh Nhân");

        jLabel3.setForeground(new java.awt.Color(51, 204, 255));
        jLabel3.setText("Mã Bác Sĩ");

        jLabel4.setForeground(new java.awt.Color(51, 204, 255));
        jLabel4.setText("Ngày Hẹn");

        jLabel6.setForeground(new java.awt.Color(51, 204, 255));
        jLabel6.setText("Giờ Hẹn");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Trạng Thái"));
        jPanel2.setForeground(new java.awt.Color(51, 204, 255));

        buttonGroup1.add(rdo_xn);
        rdo_xn.setForeground(new java.awt.Color(51, 204, 255));
        rdo_xn.setText("Đã xác nhận");

        buttonGroup1.add(rdo_cxn);
        rdo_cxn.setText("Chưa xác nhận");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdo_xn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rdo_cxn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_xn)
                    .addComponent(rdo_cxn))
                .addContainerGap())
        );

        txt_id.setForeground(new java.awt.Color(51, 204, 255));

        txt_mabn.setForeground(new java.awt.Color(51, 204, 255));

        txt_mabs.setForeground(new java.awt.Color(51, 204, 255));

        txt_ngayhen.setForeground(new java.awt.Color(51, 204, 255));

        txt_giohen.setForeground(new java.awt.Color(51, 204, 255));

        jLabel5.setForeground(new java.awt.Color(51, 204, 255));
        jLabel5.setText("Ngày Đặt Lịch");

        txt_ngaydatlich.setForeground(new java.awt.Color(51, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_mabn, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(txt_mabs, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(txt_ngayhen, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(txt_giohen, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(txt_ngaydatlich))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_mabn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_mabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_ngayhen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_giohen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_ngaydatlich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 204, 255));
        jLabel7.setText("LỊCH HẸN TÁI KHÁM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_tk))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_sua)
                            .addComponent(btn_them))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_tk)
                            .addComponent(btn_xoa))
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn THÊM không");
        if (chon == 0) {
            i = tbl_lichhen.getSelectedRow();
            try {
                if (this.readform() != null) {
                    if (rp.them(this.readform()) > 0) {
                        JOptionPane.showMessageDialog(this, "Thêm thành công");
                        this.filltotable(rp.getAll());
                    } else {
                        JOptionPane.showMessageDialog(this, "Thêm thất bại");
                    }
                }
            } catch (java.text.ParseException ex) {
                Logger.getLogger(ViewLichHen1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn SỬA không ?? ");
        if (chon == 0) {
            i = tbl_lichhen.getSelectedRow();
            int ma = Integer.parseInt(tbl_lichhen.getValueAt(i, 0).toString());
            try {
                if (this.readform() != null) {
                    if (rp.sua(ma, this.readform()) > 0) {
                        JOptionPane.showMessageDialog(this, "Sửa thành công");
                        this.filltotable(rp.getAll());
                    } else {
                        JOptionPane.showMessageDialog(this, "Sửa thất bại");
                    }
                }
            } catch (java.text.ParseException ex) {
                Logger.getLogger(ViewLichHen1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn XÓA không");
        if (chon == 0) {
            i = tbl_lichhen.getSelectedRow();
            if (i > 0) {
                int id = Integer.parseInt(tbl_lichhen.getValueAt(i, 0).toString());
                if (rp.xoa(id) > 0) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    this.filltotable(rp.getAll());
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng xóa");
            }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_tkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tkActionPerformed
        // TODO add your handling code here:
        String id = JOptionPane.showInputDialog(null, "Mời nhập ID cần tìm", "FORM TÌM KIẾM", 1);
        if (rp.tim(id).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy ID");
        } else {
            JOptionPane.showMessageDialog(this, "Có tìm thấy tên");
            this.filltotable(rp.tim(id));
        }
    }//GEN-LAST:event_btn_tkActionPerformed

    private void tbl_lichhenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_lichhenMouseClicked
        // TODO add your handling code here:
        i = tbl_lichhen.getSelectedRow();
        this.showData(i);
    }//GEN-LAST:event_tbl_lichhenMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_tk;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdo_cxn;
    private javax.swing.JRadioButton rdo_xn;
    private javax.swing.JTable tbl_lichhen;
    private javax.swing.JTextField txt_giohen;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_mabn;
    private javax.swing.JTextField txt_mabs;
    private javax.swing.JTextField txt_ngaydatlich;
    private javax.swing.JTextField txt_ngayhen;
    // End of variables declaration//GEN-END:variables
}
