/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.poly.view;

import com.poly.entity.DichVu;
import com.poly.entity.TrangChu;
import com.poly.ph49571.DichVuServices;
import com.poly.ph49571.ModeDichVu;
import com.poly.repository.RepoTrangChu;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manh9
 */
public class From_TrangChu extends javax.swing.JPanel {
  //dich vu
    List<ModeDichVu> listDV = new ArrayList<>();
    DefaultTableModel dtm = new DefaultTableModel();
    DichVuServices dvsv = new DichVuServices();
   //lich hen
    List<TrangChu> list = new ArrayList<>();
    RepoTrangChu repo = new RepoTrangChu();
   //bac sĩ
 
    public From_TrangChu() throws SQLException {
        initComponents();
        //dich vu
        getdatadichvu();
        //lich hen
        list=  repo.getAllTT();
        loadTableTT(list);
        //bac sĩ
         list =  repo.getAllBs();
        loadTableBs(list);
 }      
    //dich vu
 public void getdatadichvu() throws SQLException {
        listDV = dvsv.getdata();
        this.displayToTable(dvsv.getdata());

    }
  public void displayToTable(ArrayList<ModeDichVu> list) {
        DefaultTableModel model = (DefaultTableModel) tbDichVu.getModel();
        model.setRowCount(0);
        for (ModeDichVu dichvu : list) {
            Object[] row = {dichvu.getStt(), dichvu.getTen_dichvu(), dichvu.getMota(), dichvu.getChiphi(), dichvu.getNgaytao(), dichvu.getTrangthai()};
            model.addRow(row);
        }
    }
//lich hen
    public void loadTableTT( List<TrangChu> list){
    DefaultTableModel dtm = (DefaultTableModel) this.tbLichHen.getModel();
    dtm.setRowCount(0);
    for (TrangChu tt : list) {
        dtm.addRow(tt.rowDtTT());
    }
}
    
      //bac sĩ
    public void loadTableBs( List<TrangChu> list){
    DefaultTableModel dtm = (DefaultTableModel) this.tbBacSi.getModel();
    dtm.setRowCount(0);
    for (TrangChu tt : list) {
        dtm.addRow(tt.rowDtBs());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbBacSi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDichVu = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbLichHen = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        tbBacSi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên Bác sĩ", "Số năm kinh nghiệm", "Chuyên khoa", "SDT", "Trạng thái"
            }
        ));
        jScrollPane1.setViewportView(tbBacSi);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1.png"))); // NOI18N
        jLabel1.setText("Bác sĩ nổi bật");

        tbDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Dịch Vụ", "Mô Tả", "Chi Phí", "Trạng thái"
            }
        ));
        jScrollPane2.setViewportView(tbDichVu);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 204, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/3.png"))); // NOI18N
        jLabel3.setText("Dịch vụ toàn diện");

        tbLichHen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tên Bác sĩ", "Tên bệnh nhân", "Ngày hẹn", "Giờ hẹn", "Ngày đặt lịch", "Trạng thái"
            }
        ));
        jScrollPane3.setViewportView(tbLichHen);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 204, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/4.png"))); // NOI18N
        jLabel4.setText("Lịch hẹn ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(571, 571, 571)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(245, 245, 245))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbBacSi;
    private javax.swing.JTable tbDichVu;
    private javax.swing.JTable tbLichHen;
    // End of variables declaration//GEN-END:variables

     
}
