/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.poly.view;

import com.poly.entity.BenhAn;
import com.poly.repository.ReposBenhAn;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manh9
 */
public class From_BenhAn extends javax.swing.JPanel {
 private DefaultTableModel dtm = new DefaultTableModel();
 private List<BenhAn> listBA = new ArrayList<>();
 private ReposBenhAn repo = new ReposBenhAn();
    
    public From_BenhAn() {
        initComponents();
          listBA =  repo.getAll();
          loadTable(listBA);
    }

      public void loadTable(List<BenhAn> list){
         DefaultTableModel dtm = (DefaultTableModel) this.tbl_benhan.getModel();
        dtm.setRowCount(0);
        for (BenhAn ba : list) {
             dtm.addRow(ba.rowData());
        }
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_benhan = new javax.swing.JTable();

        tbl_benhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Bệnh Nhân", "Mã Bác Sĩ", "Chẩn Đoán", "Điều Trị", "Ngày Khám", "Ngày Lập Bệnh Án", "Mô tả", "Trạng Thái"
            }
        ));
        jScrollPane1.setViewportView(tbl_benhan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_benhan;
    // End of variables declaration//GEN-END:variables
}

 
