/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.poly.view;

import com.poly.entity.LichLamViec;
import com.poly.repository.RepoLichLamViec;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manh9
 */
public class From_LichLamViec extends javax.swing.JPanel {
 private DefaultTableModel dtm = new DefaultTableModel();
 private List<LichLamViec> listLSLV = new ArrayList<>();
 private RepoLichLamViec repo = new RepoLichLamViec();

    /**
     * Creates new form FromLichLamViec
     */
    public From_LichLamViec() {
        initComponents();
        listLSLV = repo.getAll();
        loadTable(listLSLV);
    }
  public void loadTable(List<LichLamViec> list){
        DefaultTableModel dtm = (DefaultTableModel) this.tbLichLamViec.getModel();
        dtm.setRowCount(0);
        for (LichLamViec llv : list) {
            dtm.addRow(llv.rowData());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbLichLamViec = new javax.swing.JTable();

        tbLichLamViec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MaBacSi", "Ngay", "ThoiGianBatDau", "ThoiGianKetThuc", "GhiChu", "CaLamViec", "TrangThai", "NgayTao"
            }
        ));
        jScrollPane1.setViewportView(tbLichLamViec);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbLichLamViec;
    // End of variables declaration//GEN-END:variables
}
