/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.poly.view;

import com.poly.entity.BenhNhan;
import com.poly.repository.RepoBenhNhan;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manh9
 */
public class From_BenhNhan extends javax.swing.JPanel {
 private RepoBenhNhan repo = new RepoBenhNhan();
    private DefaultTableModel dtm = new DefaultTableModel();
    private List<BenhNhan> list = new ArrayList<>();
    /**
     * Creates new form From_BenhNhan
     */
    public From_BenhNhan() {
        initComponents();
         list = repo.getall();
        loadTable(list);
    }
public void loadTable(List<BenhNhan> listBn){
         DefaultTableModel dtm = (DefaultTableModel) this.tbBenhNhan.getModel();
         dtm.setRowCount(0);
         for (BenhNhan mdBn : listBn) {
            dtm.addRow(mdBn.rowData());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbBenhNhan = new javax.swing.JTable();

        tbBenhNhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Ten", "NgaySinh", "DiaChi", "Mật khẩu", "SoDienThoai", "Email", "GioiTinh", "NgayTao", "TrangThai"
            }
        ));
        jScrollPane1.setViewportView(tbBenhNhan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbBenhNhan;
    // End of variables declaration//GEN-END:variables
}
